import React from "react";
import styles from "./Layout.css";
import Sider from "./Sider";

const Layout = () => {
  return (
    <div className={styles.aside}>
      <div className={styles.sider}>
        <div className={styles.logo}>
          <h1>Home Service</h1>
        </div>
        <Sider />
      </div>
      <div className={styles.main}>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
        <p>dsagsd</p>
      </div>
    </div>
  );
};

export default Layout;
